import assert from 'node:assert/strict'
import { describe, it } from 'node:test'

import { babyjubjub as nobleBabyJubJub } from '@noble/curves/misc.js'

import { Base8, Fr, a, addPoint, d, inCurve, mulPointEscalar, order, packPoint, r, subOrder, unpackPoint } from '../src/babyjubjub.js'
import { RailJubCurvePoint } from '../src/curve.js'

const NoblePoint = nobleBabyJubJub.Point
const nobleCurve = NoblePoint.CURVE()

/**
 * Lifts an affine pair into a noble point.
 * @param p Affine coordinates.
 * @returns The corresponding noble point.
 */
const toNoble = (p: [bigint, bigint]) => NoblePoint.fromAffine({ x: p[0], y: p[1] })

describe('Baby Jubjub curve parameters', () => {
  it('matches the EIP-2494 parameters used by @noble/curves', () => {
    assert.equal(r, nobleCurve.p)
    assert.equal(subOrder, nobleCurve.n)
    assert.equal(a, nobleCurve.a)
    assert.equal(d, nobleCurve.d)
    assert.equal(order, subOrder * nobleCurve.h)
  })

  it('uses the prime-order base point B, not the full-group generator G', () => {
    // noble historically exposed G here; a regression would silently change
    // every derived key, so pin the value rather than trusting the import.
    assert.equal(Base8[0], nobleCurve.Gx)
    assert.equal(Base8[1], nobleCurve.Gy)
    assert.equal(Base8[0], 5299619240641551281634865583518297030282874472190772894086521144482721001553n)
    assert.equal(Base8[1], 16950150798460657717958625567821834550301663161624707787222815936182638968203n)
  })

  it('places the base point in the prime-order subgroup', () => {
    assert.deepEqual(mulPointEscalar(Base8, subOrder), [0n, 1n])
    assert.ok(inCurve(Base8))
  })
})

describe('Baby Jubjub arithmetic against @noble/curves', () => {
  it('agrees on scalar multiplication of the base point', () => {
    for (let i = 1; i <= 64; i++) {
      const k = BigInt(i) * 7919n + 3n
      const mine = mulPointEscalar(Base8, k)
      const theirs = NoblePoint.BASE.multiply(k % subOrder).toAffine()
      assert.equal(mine[0], theirs.x, `x mismatch at k=${k}`)
      assert.equal(mine[1], theirs.y, `y mismatch at k=${k}`)
    }
  })

  it('agrees on point addition', () => {
    for (let i = 1; i <= 64; i++) {
      const p = mulPointEscalar(Base8, BigInt(i) * 31n + 1n)
      const q = mulPointEscalar(Base8, BigInt(i) * 977n + 5n)
      const mine = addPoint(p, q)
      const theirs = toNoble(p).add(toNoble(q)).toAffine()
      assert.equal(mine[0], theirs.x)
      assert.equal(mine[1], theirs.y)
    }
  })

  it('agrees on curve membership', () => {
    const p = mulPointEscalar(Base8, 12345n)
    assert.ok(inCurve(p))
    assert.doesNotThrow(() => toNoble(p).assertValidity())

    const offCurve: [bigint, bigint] = [p[0] + 1n, p[1]]
    assert.ok(!inCurve(offCurve))
    assert.throws(() => toNoble(offCurve).assertValidity())
  })
})

describe('Baby Jubjub scalar multiplication edge cases', () => {
  it('accepts the zero scalar and returns the identity', () => {
    assert.deepEqual(mulPointEscalar(Base8, 0n), [0n, 1n])
  })

  it('accepts scalars at or above the subgroup order', () => {
    // DeserializeElement multiplies an untrusted point by subOrder to test
    // membership, so out-of-range scalars must not be rejected or reduced.
    assert.deepEqual(mulPointEscalar(Base8, subOrder), [0n, 1n])
    assert.deepEqual(mulPointEscalar(Base8, order), [0n, 1n])
    assert.deepEqual(mulPointEscalar(Base8, subOrder + 1n), Base8)
  })

  it('detects a point outside the prime-order subgroup', () => {
    // (0, -1) has order 2 and lies outside the subgroup generated by Base8.
    const orderTwo: [bigint, bigint] = [0n, r - 1n]
    assert.ok(inCurve(orderTwo))
    assert.notDeepEqual(mulPointEscalar(orderTwo, subOrder), [0n, 1n])
  })
})

describe('Baby Jubjub point compression', () => {
  it('round-trips every packed point', () => {
    for (let i = 1; i <= 128; i++) {
      const p = mulPointEscalar(Base8, BigInt(i) * 104729n + 7n)
      const unpacked = unpackPoint(packPoint(p))
      assert.notEqual(unpacked, null)
      assert.deepEqual(unpacked, p)
    }
  })

  it('signs on the balanced ordering, not RFC 8032 parity', () => {
    // circomlib sets the sign bit when x exceeds (r - 1) / 2; RFC 8032 sets it
    // on the parity of x. The two agree only about half the time, and both
    // encodings are live in this package: packPoint feeds RAILGUN addresses and
    // Circom witnesses, SerializeElement feeds the FROST transcript.
    const curve = new RailJubCurvePoint()
    let differed = 0

    for (let i = 1; i <= 128; i++) {
      const p = mulPointEscalar(Base8, BigInt(i) * 7919n + 3n)
      const packedSign = (packPoint(p) >> 255n) & 1n
      const paritySign = p[0] & 1n
      if (packedSign !== paritySign) differed++

      const half = (r - 1n) / 2n
      assert.equal(packedSign, p[0] > half ? 1n : 0n)

      // SerializeElement must keep using parity.
      const serialized = curve.SerializeElement(p)
      assert.equal(BigInt(serialized[31]! >> 7), paritySign)
    }

    assert.ok(differed > 0, 'the two sign conventions must not have been unified')
  })

  it('rejects a y-coordinate above the field prime', () => {
    assert.equal(unpackPoint(r + 1n), null)
  })

  it('rejects a y-coordinate with no matching x', () => {
    assert.equal(unpackPoint(2n), null)
  })
})

describe('Fr field helpers', () => {
  it('orders elements on the balanced representation', () => {
    const half = (r - 1n) / 2n
    assert.ok(!Fr.lt(half, Fr.zero))
    assert.ok(Fr.lt(half + 1n, Fr.zero))
    assert.ok(Fr.geq(half, Fr.zero))
    assert.ok(!Fr.geq(half + 1n, Fr.zero))
  })

  it('inverts and divides consistently', () => {
    for (let i = 1; i <= 64; i++) {
      const x = BigInt(i) * 1234567891011n + 7n
      assert.equal(Fr.mul(x, Fr.inv(x)), 1n)
      assert.equal(Fr.div(x, 3n), Fr.mul(x, Fr.inv(3n)))
    }
  })

  it('refuses to invert zero', () => {
    assert.throws(() => Fr.inv(0n), /not invertible/)
  })
})
