/**
 * Baby Jubjub curve arithmetic, serialization, and field helpers.
 *
 * A dependency-free implementation of the affine twisted Edwards operations
 * this package needs, so nothing here pulls a Node-only byte polyfill into the
 * bundle.
 *
 * Point compression follows circomlib's convention: `x` counts as negative when
 * it exceeds `(r - 1) / 2`. This is **not** RFC 8032 parity. See `curve.ts` for
 * the RFC 8032 encoding used by the FROST transcript; the two intentionally
 * differ and must not be unified.
 *
 * Curve parameters follow EIP-2494.
 * @see {@link https://eips.ethereum.org/EIPS/eip-2494}
 * @module
 */

/** Affine curve point as an `[x, y]` pair. */
type Point<N = bigint> = [N, N]

/** Base field prime: the scalar field order of BN254. */
const r = 21888242871839275222246405745257275088548364400416034343698204186575808495617n

/** Order of the full curve group (`8 * subOrder`). */
const order = 21888242871839275222246405745257275088614511777268538073601725287587578984328n

/** Order of the prime-order subgroup generated by `Base8`. */
const subOrder = 2736030358979909402780800718157159386076813972158567259200215660948447373041n

/** Twisted Edwards coefficient `a`. */
const a = 168700n

/** Twisted Edwards coefficient `d`. */
const d = 168696n

/** Generator of the prime-order subgroup (EIP-2494 `B = 8 * G`). */
const Base8: Point<bigint> = [
  5299619240641551281634865583518297030282874472190772894086521144482721001553n,
  16950150798460657717958625567821834550301663161624707787222815936182638968203n,
]

/** Midpoint of the base field, the threshold of the balanced representation. */
const HALF = (r - 1n) / 2n

/**
 * Reduces a value into `[0, r)`.
 * @param x Value to reduce.
 * @returns The canonical representative.
 */
const mod = (x: bigint): bigint => {
  const v = x % r
  return v < 0n ? v + r : v
}

/**
 * Maps a field element to its balanced representative in `(-r/2, r/2]`.
 *
 * Under this ordering `lt(x, 0)` is true exactly when `x > (r - 1) / 2`. The
 * point compression sign bit depends on it.
 * @param x Field element in `[0, r)`.
 * @returns The signed representative.
 */
const balanced = (x: bigint): bigint => (x > HALF ? x - r : x)

/**
 * Computes a modular inverse by the extended Euclidean algorithm.
 * @param x Value to invert.
 * @returns The inverse of `x` modulo `r`.
 * @throws If `x` is zero modulo `r`. {@link Error}
 */
const inv = (x: bigint): bigint => {
  let t = 0n
  let newT = 1n
  let rr = r
  let newR = mod(x)
  while (newR !== 0n) {
    const q = rr / newR
    ;[t, newT] = [newT, t - q * newT]
    ;[rr, newR] = [newR, rr - q * newR]
  }
  if (rr !== 1n) throw new Error('Fr: value is not invertible')
  return mod(t)
}

/**
 * Computes modular exponentiation.
 * @param base Base value.
 * @param exp Non-negative exponent.
 * @returns `base ** exp` modulo `r`.
 */
const pow = (base: bigint, exp: bigint): bigint => {
  let result = 1n
  let b = mod(base)
  let e = exp
  while (e > 0n) {
    if (e & 1n) result = mod(result * b)
    b = mod(b * b)
    e >>= 1n
  }
  return result
}

/**
 * Minimal field-arithmetic helper over the Baby Jubjub base field.
 *
 * Mirrors the `F1Field` surface that consumers reading `RailJubCurvePoint.Fr`
 * expect, using the same balanced ordering for comparisons.
 */
const Fr = {
  /** Field modulus. */
  p: r,
  /** Additive identity. */
  zero: 0n,
  /** Multiplicative identity. */
  one: 1n,
  /** Midpoint used by the balanced ordering. */
  _half: HALF,
  /** Additive inverse of one. */
  _negone: r - 1n,
  /**
   * Reduces an arbitrary integer into the field.
   * @param x Value to reduce.
   * @returns The canonical representative.
   */
  e: (x: bigint): bigint => mod(x),
  /**
   * Adds two field elements.
   * @param x First operand.
   * @param y Second operand.
   * @returns The sum.
   */
  add: (x: bigint, y: bigint): bigint => mod(x + y),
  /**
   * Subtracts two field elements.
   * @param x Minuend.
   * @param y Subtrahend.
   * @returns The difference.
   */
  sub: (x: bigint, y: bigint): bigint => mod(x - y),
  /**
   * Negates a field element.
   * @param x Value to negate.
   * @returns The additive inverse.
   */
  neg: (x: bigint): bigint => mod(-x),
  /**
   * Multiplies two field elements.
   * @param x First operand.
   * @param y Second operand.
   * @returns The product.
   */
  mul: (x: bigint, y: bigint): bigint => mod(x * y),
  /**
   * Squares a field element.
   * @param x Value to square.
   * @returns The square.
   */
  square: (x: bigint): bigint => mod(x * x),
  /**
   * Divides two field elements.
   * @param x Numerator.
   * @param y Denominator.
   * @returns The quotient.
   */
  div: (x: bigint, y: bigint): bigint => mod(x * inv(y)),
  /**
   * Inverts a field element.
   * @param x Value to invert.
   * @returns The multiplicative inverse.
   */
  inv: (x: bigint): bigint => inv(x),
  /**
   * Raises a field element to a power.
   * @param x Base.
   * @param e Exponent.
   * @returns The result.
   */
  pow: (x: bigint, e: bigint): bigint => pow(x, e),
  /**
   * Tests equality of two field elements.
   * @param x First operand.
   * @param y Second operand.
   * @returns `true` when the two are equal.
   */
  eq: (x: bigint, y: bigint): boolean => mod(x) === mod(y),
  /**
   * Tests whether a field element is zero.
   * @param x Value to test.
   * @returns `true` when the value is zero.
   */
  isZero: (x: bigint): boolean => mod(x) === 0n,
  /**
   * Compares two field elements in the balanced representation.
   * @param x First operand.
   * @param y Second operand.
   * @returns `true` when `x` sorts before `y`.
   */
  lt: (x: bigint, y: bigint): boolean => balanced(mod(x)) < balanced(mod(y)),
  /**
   * Compares two field elements in the balanced representation.
   * @param x First operand.
   * @param y Second operand.
   * @returns `true` when `x` sorts after `y`.
   */
  gt: (x: bigint, y: bigint): boolean => balanced(mod(x)) > balanced(mod(y)),
  /**
   * Compares two field elements in the balanced representation.
   * @param x First operand.
   * @param y Second operand.
   * @returns `true` when `x` sorts at or after `y`.
   */
  geq: (x: bigint, y: bigint): boolean => balanced(mod(x)) >= balanced(mod(y)),
  /**
   * Compares two field elements in the balanced representation.
   * @param x First operand.
   * @param y Second operand.
   * @returns `true` when `x` sorts at or before `y`.
   */
  leq: (x: bigint, y: bigint): boolean => balanced(mod(x)) <= balanced(mod(y)),
}

/**
 * Computes a modular square root by Tonelli-Shanks.
 *
 * The base field satisfies `r - 1 = Q * 2^28`, so no closed-form root exists
 * and the general algorithm is required. The returned root is canonicalized to
 * the non-negative half of the balanced representation, which is what point
 * decompression relies on to recover the sign.
 * @param n Value whose square root is sought.
 * @returns The canonical square root, or `null` when `n` is not a residue.
 */
const sqrt = (n: bigint): bigint | null => {
  const v = mod(n)
  if (v === 0n) return 0n

  // r - 1 = Q * 2^S with Q odd.
  const S = 28n
  const Q = (r - 1n) >> S

  // Euler's criterion.
  if (pow(v, (r - 1n) / 2n) !== 1n) return null

  // Any quadratic non-residue works as the generator of the 2-Sylow subgroup.
  let z = 2n
  while (pow(z, (r - 1n) / 2n) === 1n) z += 1n

  let m = S
  let c = pow(z, Q)
  let t = pow(v, Q)
  let x = pow(v, (Q + 1n) / 2n)

  while (t !== 1n) {
    let i = 0n
    let t2 = t
    while (t2 !== 1n) {
      t2 = mod(t2 * t2)
      i += 1n
    }
    let b = c
    for (let j = 0n; j < m - i - 1n; j += 1n) b = mod(b * b)
    m = i
    c = mod(b * b)
    t = mod(t * c)
    x = mod(x * b)
  }

  // Canonicalize: return the root in the non-negative balanced half.
  return x > HALF ? mod(-x) : x
}

/**
 * Adds two points on the curve.
 * @param p1 First point.
 * @param p2 Second point.
 * @returns The sum of the two points.
 */
const addPoint = (p1: Point<bigint>, p2: Point<bigint>): Point<bigint> => {
  const beta = mod(p1[0] * p2[1])
  const gamma = mod(p1[1] * p2[0])
  const delta = mod(mod(p1[1] - mod(a * p1[0])) * mod(p2[0] + p2[1]))
  const tau = mod(beta * gamma)
  const dtau = mod(d * tau)

  const x3 = mod(mod(beta + gamma) * inv(mod(1n + dtau)))
  const y3 = mod(mod(delta + mod(mod(a * beta) - gamma)) * inv(mod(1n - dtau)))

  return [x3, y3]
}

/**
 * Multiplies a point by a scalar.
 *
 * Accepts any non-negative scalar, including values at or above the subgroup
 * order, and any point on the curve, including points outside the prime-order
 * subgroup. Callers rely on both: `DeserializeElement` multiplies an untrusted
 * point by the subgroup order to test membership.
 * @param base Point to multiply.
 * @param e Non-negative scalar.
 * @returns The resulting point.
 */
const mulPointEscalar = (base: Point<bigint>, e: bigint): Point<bigint> => {
  let res: Point<bigint> = [0n, 1n]
  let rem = e
  let exp = base

  while (rem !== 0n) {
    if (rem & 1n) res = addPoint(res, exp)
    exp = addPoint(exp, exp)
    rem >>= 1n
  }

  return res
}

/**
 * Tests whether a point satisfies the curve equation.
 * @param p Point to test.
 * @returns `true` when the point lies on the curve.
 */
const inCurve = (p: Point<bigint | string | number>): boolean => {
  const x1 = BigInt(p[0])
  const y1 = BigInt(p[1])
  const x2 = mod(x1 * x1)
  const y2 = mod(y1 * y1)

  return mod(mod(a * x2) + y2) === mod(1n + mod(mod(x2 * y2) * d))
}

/**
 * Compresses a point into a single field-sized integer.
 *
 * The y-coordinate occupies the low 255 bits; bit 255 carries the sign of `x`
 * under the balanced ordering (`x > (r - 1) / 2`). This is circomlib's
 * convention and is what RAILGUN addresses and Circom witnesses expect.
 * @param unpackedPoint Point to compress.
 * @returns The compressed representation.
 */
const packPoint = (unpackedPoint: Point<bigint>): bigint => {
  const y = unpackedPoint[1]
  const signBit = balanced(mod(unpackedPoint[0])) < 0n ? 1n << 255n : 0n

  return y | signBit
}

/**
 * Decompresses a point produced by {@link packPoint}.
 * @param packedPoint Compressed point.
 * @returns The affine point, or `null` when the encoding does not decode.
 */
const unpackPoint = (packedPoint: bigint): Point<bigint> | null => {
  const sign = (packedPoint >> 255n) & 1n
  const y = packedPoint & ((1n << 255n) - 1n)

  if (y > r) return null

  const y2 = mod(y * y)
  const root = sqrt(mod(mod(1n - y2) * inv(mod(a - mod(d * y2)))))
  if (root === null) return null

  return [sign === 1n ? mod(-root) : root, y]
}

export type { Point }
export { Base8, Fr, a, addPoint, d, inCurve, mulPointEscalar, order, packPoint, r, subOrder, unpackPoint }
